/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AssessmentEvidenceRegistry__factory } from "./AssessmentEvidenceRegistry__factory";
export { ConsultationEvidenceRegistry__factory } from "./ConsultationEvidenceRegistry__factory";
