/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AssessmentEvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAssessmentRevisionCount"
      | "getAuthorizationHash"
      | "getLatestAssessmentEvidence"
      | "owner"
      | "recordAssessment"
      | "recordAssessmentWithSignature"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AssessmentRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAssessmentRevisionCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthorizationHash",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestAssessmentEvidence",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAssessment",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordAssessmentWithSignature",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAssessmentRevisionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorizationHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestAssessmentEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAssessmentWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AssessmentRecordedEvent {
  export type InputTuple = [
    assessmentKey: BytesLike,
    assessmentType: BigNumberish,
    recordHash: BytesLike,
    revision: BigNumberish,
    recordedAt: BigNumberish,
    operator: AddressLike
  ];
  export type OutputTuple = [
    assessmentKey: string,
    assessmentType: bigint,
    recordHash: string,
    revision: bigint,
    recordedAt: bigint,
    operator: string
  ];
  export interface OutputObject {
    assessmentKey: string;
    assessmentType: bigint;
    recordHash: string;
    revision: bigint;
    recordedAt: bigint;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssessmentEvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AssessmentEvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: AssessmentEvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAssessmentRevisionCount: TypedContractMethod<
    [assessmentKey: BytesLike],
    [bigint],
    "view"
  >;

  getAuthorizationHash: TypedContractMethod<
    [
      assessmentKey: BytesLike,
      assessmentType: BigNumberish,
      recordHash: BytesLike
    ],
    [string],
    "view"
  >;

  getLatestAssessmentEvidence: TypedContractMethod<
    [assessmentKey: BytesLike],
    [
      [bigint, string, bigint, bigint, string] & {
        assessmentType: bigint;
        recordHash: string;
        revision: bigint;
        recordedAt: bigint;
        operator: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordAssessment: TypedContractMethod<
    [
      assessmentKey: BytesLike,
      assessmentType: BigNumberish,
      recordHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  recordAssessmentWithSignature: TypedContractMethod<
    [
      assessmentKey: BytesLike,
      assessmentType: BigNumberish,
      recordHash: BytesLike,
      ownerSignature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAssessmentRevisionCount"
  ): TypedContractMethod<[assessmentKey: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAuthorizationHash"
  ): TypedContractMethod<
    [
      assessmentKey: BytesLike,
      assessmentType: BigNumberish,
      recordHash: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestAssessmentEvidence"
  ): TypedContractMethod<
    [assessmentKey: BytesLike],
    [
      [bigint, string, bigint, bigint, string] & {
        assessmentType: bigint;
        recordHash: string;
        revision: bigint;
        recordedAt: bigint;
        operator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordAssessment"
  ): TypedContractMethod<
    [
      assessmentKey: BytesLike,
      assessmentType: BigNumberish,
      recordHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordAssessmentWithSignature"
  ): TypedContractMethod<
    [
      assessmentKey: BytesLike,
      assessmentType: BigNumberish,
      recordHash: BytesLike,
      ownerSignature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AssessmentRecorded"
  ): TypedContractEvent<
    AssessmentRecordedEvent.InputTuple,
    AssessmentRecordedEvent.OutputTuple,
    AssessmentRecordedEvent.OutputObject
  >;

  filters: {
    "AssessmentRecorded(bytes32,uint8,bytes32,uint256,uint256,address)": TypedContractEvent<
      AssessmentRecordedEvent.InputTuple,
      AssessmentRecordedEvent.OutputTuple,
      AssessmentRecordedEvent.OutputObject
    >;
    AssessmentRecorded: TypedContractEvent<
      AssessmentRecordedEvent.InputTuple,
      AssessmentRecordedEvent.OutputTuple,
      AssessmentRecordedEvent.OutputObject
    >;
  };
}
