/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ConsultationEvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAuthorizationHash"
      | "getConsultationRevisionCount"
      | "getLatestConsultationEvidence"
      | "owner"
      | "recordConsultation"
      | "recordConsultationWithSignature"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ConsultationRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAuthorizationHash",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConsultationRevisionCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestConsultationEvidence",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordConsultation",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordConsultationWithSignature",
    values: [string, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAuthorizationHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConsultationRevisionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestConsultationEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordConsultation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordConsultationWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ConsultationRecordedEvent {
  export type InputTuple = [
    consultationId: string,
    appointmentId: string,
    recordHash: BytesLike,
    revision: BigNumberish,
    recordedAt: BigNumberish,
    operator: AddressLike
  ];
  export type OutputTuple = [
    consultationId: string,
    appointmentId: string,
    recordHash: string,
    revision: bigint,
    recordedAt: bigint,
    operator: string
  ];
  export interface OutputObject {
    consultationId: string;
    appointmentId: string;
    recordHash: string;
    revision: bigint;
    recordedAt: bigint;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConsultationEvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ConsultationEvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: ConsultationEvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAuthorizationHash: TypedContractMethod<
    [consultationId: string, appointmentId: string, recordHash: BytesLike],
    [string],
    "view"
  >;

  getConsultationRevisionCount: TypedContractMethod<
    [consultationId: string],
    [bigint],
    "view"
  >;

  getLatestConsultationEvidence: TypedContractMethod<
    [consultationId: string],
    [
      [string, string, bigint, bigint, string] & {
        appointmentId: string;
        recordHash: string;
        revision: bigint;
        recordedAt: bigint;
        operator: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordConsultation: TypedContractMethod<
    [consultationId: string, appointmentId: string, recordHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  recordConsultationWithSignature: TypedContractMethod<
    [
      consultationId: string,
      appointmentId: string,
      recordHash: BytesLike,
      ownerSignature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAuthorizationHash"
  ): TypedContractMethod<
    [consultationId: string, appointmentId: string, recordHash: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConsultationRevisionCount"
  ): TypedContractMethod<[consultationId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestConsultationEvidence"
  ): TypedContractMethod<
    [consultationId: string],
    [
      [string, string, bigint, bigint, string] & {
        appointmentId: string;
        recordHash: string;
        revision: bigint;
        recordedAt: bigint;
        operator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordConsultation"
  ): TypedContractMethod<
    [consultationId: string, appointmentId: string, recordHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordConsultationWithSignature"
  ): TypedContractMethod<
    [
      consultationId: string,
      appointmentId: string,
      recordHash: BytesLike,
      ownerSignature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ConsultationRecorded"
  ): TypedContractEvent<
    ConsultationRecordedEvent.InputTuple,
    ConsultationRecordedEvent.OutputTuple,
    ConsultationRecordedEvent.OutputObject
  >;

  filters: {
    "ConsultationRecorded(string,string,bytes32,uint256,uint256,address)": TypedContractEvent<
      ConsultationRecordedEvent.InputTuple,
      ConsultationRecordedEvent.OutputTuple,
      ConsultationRecordedEvent.OutputObject
    >;
    ConsultationRecorded: TypedContractEvent<
      ConsultationRecordedEvent.InputTuple,
      ConsultationRecordedEvent.OutputTuple,
      ConsultationRecordedEvent.OutputObject
    >;
  };
}
