/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssessmentEvidenceRegistry } from "./AssessmentEvidenceRegistry";
export type { ConsultationEvidenceRegistry } from "./ConsultationEvidenceRegistry";
export * as factories from "./factories";
export { AssessmentEvidenceRegistry__factory } from "./factories/AssessmentEvidenceRegistry__factory";
export { ConsultationEvidenceRegistry__factory } from "./factories/ConsultationEvidenceRegistry__factory";
